// Name:店名、市内に2店舗以上ある場合支店名(地域名)も書く、Id:ドメイン
// Genre:ご飯物、ラーメン、そば、パスタ、パン [rice,ramen,soba,pasta,pan]
// Score:[味,量,値段]
// Cycle:自転車で何分か、Opened:開店時間(ラストオーダーを閉店時間とする)
// Map:GoogleMapの検索ワード
// Pay:[PayPay,クレカ,電子マネー]　Parking：[駐車場,駐輪場]

const [rice,ramen,soba,pasta,pan] = ["ご飯物","ラーメン","そば","パスタ","パン"]

const List = [
  {
    Name: "でんでん",
    Id: "denden",
    Genre: rice,
    Score:[4,5,4],
    Cycle: 6,
    Opened: [1130,1430,1730,2200],
    Map: "でんでん",
    Pay: [true,false,false],
    Parking: [true,true],
  },
  {
    Name: "満月や",
    Id: "mangetsuya",
    Genre: rice,
    Score:[5,3,3],
    Cycle: 7,
    Opened: [1130,1500,1700,2200],
    Map: "満月や",
    Pay: [true,false,false],
    Parking: [true,true],
  },
  {
    Name: "メーヤウ(桐)",
    Id: "kirime-yau",
    Genre: rice,
    Score:[4,5,3],
    Cycle: 3,
    Opened: [1130,2100],
    Map: "メーヤウ 桐店",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "メーヤウ(信大前)",
    Id: "shindaime-yau",
    Genre: rice,
    Score:[4,4,3],
    Cycle: 1,
    Opened: [1130,2100],
    Map: "メーヤウ 信大前店",
    Pay: [false,false,false],
    Parking: [false,false],
  },
  {
    Name: "麺匠佐蔵",
    Id: "menshosakura",
    Genre: ramen,
    Score:[5,4,3],
    Cycle: 13,
    Opened: [1130,1500,1730,2200],
    Map: "麺匠佐蔵",
    Pay: [true,false,false],
    Parking: [true,false],
  },
  {
    Name: "がったぼうず",
    Id: "gattabozu",
    Genre: ramen,
    Score:[5,4,3],
    Cycle: 7,
    Opened: [1100,1500,1730,2300],
    Map: "がったぼうず",
    Pay: [true,false,false],
    Parking: [true,true],
  },
  {
    Name: "そらや",
    Id: "soraya",
    Genre: ramen,
    Score:[5,4,3],
    Cycle: 5,
    Opened: [1100,1430,1700,2100],
    Map: "札幌らーめん そらや",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "がねいしゃ",
    Id: "ganeisha",
    Genre: rice,
    Score:[5,3,4],
    Cycle: 8,
    Opened: [1130,1400,1800,2200],
    Map: "がねいしゃ",
    Pay: [false,false,false],
    Parking: [false,false],
  },
  {
    Name: "龍華楼",
    Id: "ryukaro",
    Genre: ramen,
    Score:[3,5,4],
    Cycle: 2,
    Opened: [1100,1430,1700,2300],
    Map: "龍華楼",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "麺51",
    Id: "menkoi",
    Genre: ramen,
    Score:[4,5,4],
    Cycle: 3,
    Opened: [1130,1430,1730,2130],
    Map: "麺51",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "おおぼし(桐)",
    Id: "kiriooboshi",
    Genre: ramen,
    Score:[4,4,4],
    Cycle: 3,
    Opened: [1100,1500,1730,2100],
    Map: "おおぼし 松本桐店",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "Ecru(えくりゅ)",
    Id: "ecru",
    Genre: pan,
    Score:[5,3,5],
    Cycle: 4,
    Opened: [730,1800],
    Map: "パン焼き工房エクリュ",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "紅葉",
    Id: "koyo",
    Genre: ramen,
    Score:[4,5,5],
    Cycle: 8,
    Opened: [1100,1430,1700,2300],
    Map: "紅葉",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "潮騒",
    Id: "shiosai",
    Genre: rice,
    Score:[4,5,5],
    Cycle: 15,
    Opened: [1130,1400,1800,2130],
    Map: "潮騒",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "どん八",
    Id: "dompachi",
    Genre: rice,
    Score:[5,4,4],
    Cycle: 16,
    Opened: [1115,1500,1700,2000],
    Map: "海鮮丼どん八 松本駅前本店",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "河昌",
    Id: "kawasho",
    Genre: rice,
    Score:[5,4,4],
    Cycle: 7,
    Opened: [1130,1330,1700,2100],
    Map: "河昌",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "楽座",
    Id: "rakuza",
    Genre: soba,
    Score:[5,4,4],
    Cycle: 8,
    Opened: [1100,1900],
    Map: "らくざ",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "ピカドン",
    Id: "pikadon",
    Genre: rice,
    Score:[5,4,4],
    Cycle: 1,
    Opened: [1130,1400,1730,2100],
    Map: "ピカドン",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "テンホウ",
    Id: "tenho",
    Genre: ramen,
    Score:[5,4,4],
    Cycle: 2,
    Opened: [1100,2130],
    Map: "テンホウ松本追分店",
    Pay: [true,true,true],
    Parking: [true,true],
  },
  {
    Name: "まんま",
    Id: "mamma",
    Genre: rice,
    Score:[5,4,4],
    Cycle: 7,
    Opened: [1100,1400],
    Map: "まんま 女鳥羽",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "まんぷく亭",
    Id: "mampukutei",
    Genre: rice,
    Score:[4,3,3],
    Cycle: 9,
    Opened: [1130,1430],
    Map: "まんぷく亭",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "ビストロ鬼平",
    Id: "onihei",
    Genre: pasta,
    Score:[5,4,4],
    Cycle: 8,
    Opened: [1200,1400,1800,2045],
    Map: "ビストロ鬼平",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "鎌倉パスタ",
    Id: "kamakurapasuta",
    Genre: pasta,
    Score:[5,4,4],
    Cycle: 12,
    Opened: [1100,2100],
    Map: "鎌倉パスタ　イオンモール松本店",
    Pay: [false,false,false],
    Parking: [true,true],
  },
  {
    Name: "DOLCE/かつ富",
    Id: "dolce",
    Genre: rice,
    Score:[5,4,4],
    Cycle: 7,
    Opened: [1130,1400,1730,2100],
    Map: "DOLCEかつ富",
    Pay: [true,false,false],
    Parking: [true,true],
  },
];

export default List;
  